name: Windows 11 via Tailscale RDP

on:
  workflow_dispatch:

jobs:
  tailscale_rdp:
    runs-on: windows-latest
    steps:
    - name: Enable RDP
      shell: pwsh
      run: |
        Write-Host "Enabling RDP access..."
        Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Write-Host "RDP Enabled!"

    - name: Install and Connect Tailscale
      shell: pwsh
      run: |
        Write-Host "Downloading and installing Tailscale..."
        Invoke-WebRequest https://pkgs.tailscale.com/stable/tailscale-setup-latest.exe -OutFile tailscale-setup.exe
        Start-Process .\tailscale-setup.exe -ArgumentList "/install /quiet" -Wait
        $env:Path += ";C:\Program Files\Tailscale"
        & "C:\Program Files\Tailscale\tailscale.exe" up --authkey "${{ secrets.TAILSCALE_KEY }}" --hostname GitHubRDP --accept-routes --accept-dns=false
        Write-Host "Tailscale connected successfully!"

    - name: Keep Alive
      shell: pwsh
      run: |
        Write-Host "RDP + Tailscale active. Keeping session alive..."
        while ($true) { Start-Sleep -Seconds 300 }
