name: Windows 11 via Tailscale RDP

on:
  workflow_dispatch:

jobs:
  tailscale_rdp:
    runs-on: windows-latest
    steps:
    - name: Enable RDP
      shell: pwsh
      run: |
        Write-Host "Enabling RDP access..."
        Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Write-Host "RDP Enabled!"

    - name: Install Tailscale
      shell: pwsh
      run: |
        Invoke-WebRequest https://pkgs.tailscale.com/stable/tailscale-setup-latest.exe -OutFile tailscale.exe
        Start-Process tailscale.exe -ArgumentList "/quiet" -Wait
        tailscale up --authkey ${{ secrets.TAILSCALE_KEY }} --hostname "GitHubRDP"

    - name: Keep Alive
      shell: pwsh
      run: |
        Write-Host "RDP + Tailscale active. Preventing timeout..."
        while ($true) { Start-Sleep -Seconds 300 }
